### ISSUE TITLE
SampleHeightMostDetailed compared to raycast results

### ISSUE THREAD

**Issue by ClaudeMCL** [CesiumGS/cesium-native#1015]
Running Cesium for Unity 1.13.1

In my tests I run a whole lot of raycast tests to find the Unity coordinates position of the ground to place objects, and I calculate them back to wgs84 elevation values to store them along their lat/lon geo position

I thought to replace these ray casts by SampleHeightMostDetailed, avoiding the need to bring the camera to the area to have rendered tiles for the ray cast.

As a result, my SampleHeightMostDetailed elevations lie more than 10 meters under the ray casted ones, which are positioned perfectly on the 3D tiles.

I am using the basic Bing height field 3D tiles. Here you have a few examples from my test:
0) RAYCAST Lat:32.0225895910763 Lon:34.7422150351583 Elevation:30.33143
0) SampleHeightMostDetailed Lat:32.0225895910763 Lon:34.7422150351583 Elevation:5.95650578813202

1) RAYCAST Lat:32.022663960431 Lon:34.7422311172363 Elevation:30.30002
1) SampleHeightMostDetailed Lat:32.022663960431 Lon:34.7422311172363 Elevation:15.5279202689037

2) RAYCAST Lat:32.0227540525309 Lon:34.7422266689102 Elevation:30.2398
2) SampleHeightMostDetailed Lat:32.0227540525309 Lon:34.7422266689102 Elevation:15.5287503756465

all following samples seem to have the same elevation difference between raycast and SampleHeightMostDetailed, like sample 1.

To Isolate the test I have a simple setup with a cube as seen on the screenshot.

An I attached a simple script to the cube :

using System.Collections;
using System.Collections.Generic;
using CesiumForUnity;
using Unity.VisualScripting;
using UnityEngine;

public class elevationtest : MonoBehaviour
{
    public Cesium3DTileset tileSet = null;
    public async void Start()
    {
        Unity.Mathematics.double3[] positions = new Unity.Mathematics.double3[1];
        positions[0].x = 32.0225895910763;
        positions[0].y = 34.7422150351583;
        positions[0].z = 0;
        CesiumSampleHeightResult hr = await tileSet.SampleHeightMostDetailed(positions);
        if (hr.longitudeLatitudeHeightPositions.Length > 0)
        {
            Debug.Log("Elevation found Lat:" + hr.longitudeLatitudeHeightPositions[0].x + " Lon:" + hr.longitudeLatitudeHeightPositions[0].y + " Elevation:" + hr.longitudeLatitudeHeightPositions[0].z);
        }
    }
}

which gives me as debug.log : Elevation found Lat:32.0225895910763 Lon:34.7422150351583 Elevation:5.95650578786281

The cubes H is set to 30 and SampleHeightMostDetailed return 5.95

Did I not get the concept of SampleHeightMostDetailed right ? Or is there an issue in the calculation ?

Thanks !

<img width="1702" alt="Screenshot 2024-11-27 at 12 29 40" src="https://github.com/user-attachments/assets/d01a34de-16f0-4633-8aea-3595effcd320">

**Comment by j9liu** [comment]
Hi @ClaudeMCL,

Please direct questions to our [community forum](https://community.cesium.com/). We reserve Github for confirmed bug reports and feature requests.

The height returned by `SampleHeightMostDetailed` is the height of the point above the WGS84 ellipsoid, which is the ellipsoid model used by Cesium for Unity. This is not necessary equal to the height above the _terrain_. So that could be one source of the difference.

The second is that `SampleHeightMostDetailed` samples the terrain at the _highest level of detail_. From your screenshot, it looks like the terrain is at a lower level of detail, so the cube will look misaligned. I don't know what settings you're using on Cesium World Terrain, but you may want to lower the **Maximum Screen Space Error** so that higher levels of detail are prompted to load.

I hope that helps. If you still have questions or need help, please feel free to post on the community forum :smile:
