### ISSUE TITLE
Single-frame holes in terrain when zooming out

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#186]
I've noticed that when zooming out quickly, there are often quick flickers of tiles missing. Unlike the holes that sometimes appear while panning, these tiles are missing for just one frame and then the tile reappears.

I added some code to add a border around all imagery tiles, recorded a video, and then stepped frame-by-frame through a section where I saw a tile flash.

The frame before, it looks like this:
![image](https://user-images.githubusercontent.com/924374/112280608-49ddda00-8cd9-11eb-8254-a9470620fc6d.png)

Then the problem frame looks like this:
![image](https://user-images.githubusercontent.com/924374/112280428-1dc25900-8cd9-11eb-9c3d-d76f1faeed38.png)

And the frame after is this:
![image](https://user-images.githubusercontent.com/924374/112280707-6843d580-8cd9-11eb-8570-80b9422740c7.png)

So we can clearly see from the pattern of red lines delineating raster tiles that this is a problem of geometry missing, rather than raster overlays missing.

We can also see that we're right at the point where a geometry tile suddenly meets the SSE and so it is no longer necessary to refine and render its four children. But, for reasons that are unclear, we fail to render that parent tile and instead there's a hole.

I don't _think_ the problem is that the parent tile isn't loaded yet... if that were the case, the tile would be missing for more than one frame. And also, the algorithm is supposed to keep rendering the four children in that scenario, until the parent has a chance to load.

I don't yet know why that tile is failing to render.

**Comment by baothientran** [comment]
@kring is this what you are seeing? Around 00:00:06, there are empty space flickering real quick though parent tiles are available in the previous frame and higher level tiles re-appear gain in the next frame

https://user-images.githubusercontent.com/20376598/115775176-8821f400-a380-11eb-9e3a-a2a806507491.mp4

**Comment by kring** [comment]
Yeah that looks like it @baothientran.

**Comment by baothientran** [comment]
I begin thinking this is something related to Unreal Rendering rather than the selection algorithm. Below is the video capture of the states of the tiles

https://user-images.githubusercontent.com/20376598/116465493-4dfe9980-a83b-11eb-8c6d-b6aa4f7875b5.mp4

The problem happens around 00:00:07 in the video. But below is the screenshot of the problematic tile:

Before the flickering:

![Before](https://user-images.githubusercontent.com/20376598/116468796-4e009880-a83f-11eb-9c8e-fb1e1f8353f9.PNG)


During the flickering:

![Flicker](https://user-images.githubusercontent.com/20376598/116468843-640e5900-a83f-11eb-9713-d738c63671ee.PNG)


After the flickering:

![After](https://user-images.githubusercontent.com/20376598/116468863-696ba380-a83f-11eb-8e46-6f5f5d6e6618.PNG)


In those captures above, the yellow number print on the top left of the screen is the most recent frame number coming from `Tileset`.

For the state of each tile printed as imagery, each tile will have two `TileSelectionResult` with it: the most current `TileSelectionResult` set by the selection algorithm (represented by **Curr** on the imagery) and the previous one from the last run of the selection algorithm (represented by **Last**). In other word, every time I save the selection result, I do something along the line:
```
void Tile::setLastSelectionState(const TileSelectionState& newState) noexcept {
    this->_prevLastSelectionState = this->_lastSelectionState;
    this->_lastSelectionState = newState;
}
```
Also the `Line` symbol printed on the imagery is the code line number where it set the `TileSelectionResult` for a tile.

I also comment out the code that unloads the tiles when cache is full just so I can rule out the issue that the flickering maybe from tile that doesn't have render resources.

You can see that during the flickering frame, the parent tile get refined and 3 of its children are displayed correctly except the last one. But I notice that the frame number where it set the `LastSelectionResult` are all the same for the tiles that displayed correctly and the glitched tile that is displayed in the next frame. So it can't be the selection algorithm here since we don't do anything extra after we set visibility to be true for component

**Comment by shehzan10** [comment]
Drive by comment - @baothientran The terrain tiles information seems like a great debug tool similar to Cesium Inspector in CesiumJS. Can we make it an easy option to use in the future?

**Comment by baothientran** [comment]
@shehzan10 I think it can be made to be more generic so that material can access tile information at runtime. It's good for debugging and later on, for styling metadata as well

**Comment by baothientran** [comment]
Also to add a note about the flickering problem, in the flickering frame (the middle one), you can see all three correct tiles have visibility set to be off at frame 364 and set to be on again at frame 376 which is the current frame number in the flickering capture. If it comes from our algorithm, the problematic tiles will have visibility set to be off at frame 364 and set to be on again at frame 377, which means it should be off more than one frame than neccessary. But that doesn't happen, so I think it maybe Unreal Engine rendering in this case

**Comment by baothientran** [comment]
This is the log for the below capture: 
[CesiumForUnrealSamples.log](https://github.com/CesiumGS/cesium-native/files/6400747/CesiumForUnrealSamples.log)

https://user-images.githubusercontent.com/20376598/116598457-d9883100-a8f4-11eb-9ad1-4b4ef05cd99b.mp4

The flickering happens around 00:00:27

Before:
![Before](https://user-images.githubusercontent.com/20376598/116599497-2fa9a400-a8f6-11eb-9745-3ee7c37c2d44.PNG)

During:
![Flicker](https://user-images.githubusercontent.com/20376598/116599533-3a643900-a8f6-11eb-81fc-c1b3ce5a5454.PNG)

After:
![After](https://user-images.githubusercontent.com/20376598/116599557-405a1a00-a8f6-11eb-8a8d-6b5a1d60674b.PNG)

The log confirms that all the tiles that are supposed to be rendered during the flickering frame (middle) are correctly added to the rendering queue by the selection algorithm. But only 2 of them are really rendered by the engine. The other two are delayed by one frame.

**Comment by kring** [comment]
So the tiles printed in the log are the new tiles in the render list that frame? Can you also print to the log whether or not the tile is truly renderable? I wouldn't be shocked to see a tile in the render list before it's totally loaded. I'd probably print both `tile.isRenderable()` and `tile.getContent() != nullptr`.

**Comment by baothientran** [comment]
This is the new log with check for tile.isRenderable() and tile.getContent() != nullptr

[CesiumForUnrealSamples.log](https://github.com/CesiumGS/cesium-native/files/6402664/CesiumForUnrealSamples.log)

https://user-images.githubusercontent.com/20376598/116640561-e2025b00-a938-11eb-8b29-d2b784a0e396.mp4

Before
![Before](https://user-images.githubusercontent.com/20376598/116640621-03634700-a939-11eb-9a28-36dcfd75a935.PNG)

During:
![Flicker](https://user-images.githubusercontent.com/20376598/116640630-08c09180-a939-11eb-84f1-5c55d9d859cd.PNG)

After:
![After](https://user-images.githubusercontent.com/20376598/116640640-0e1ddc00-a939-11eb-8a9e-637c70b279b6.PNG)

The problematic tiles all have the content available when in the render queue. Also in the new log, if you see the line `Off Visible`, it indicates the tile is in the `noLongerToRenderInThisFrame`.

**Comment by kring** [comment]
Thanks @baothientran, this is really helpful. Something a bit weird going on, though, or maybe I'm not quite sure what I'm looking at.

In frame 125 (your first screenshot), we can see that tile L15-X10492-Y23265 is being rendered. But if you look at the log for frame 125, we have:
```
[2021.04.30-02.07.15:370][126]LogCesium: Frame 125: Visible Id(level: 16, x: 20984, y: 46531) CurrState(Rendered) isRenderable(1) hasContent(1) PrevState(Rendered, frame 124)
```

The level 16 tile is a child of the level 15, so both shouldn't be in the visible list. And in fact there's no log entry for L15-X10492-Y23265 in frame 125. So it seems the screenshots and the log aren't lining up the way I expect?

**Comment by baothientran** [comment]
@kring good catch! That's definitely odd. Let me re-check again

**Comment by baothientran** [comment]
@kring This is the new log. This time I forget to put `isRenderable()` in the log itself, but it's still worth checking it out because the chance of those problematic tiles being deemed to be renderable but their contents being still loading is very low. It is because those tiles have multiple chances of being rendered before the problematic frame as the log shows. And once it is rendered, their content will never be unloaded because the code for unloadCachedTiles() is already commented out. I will have another one update soon:

[CesiumForUnrealSamples.log](https://github.com/CesiumGS/cesium-native/files/6412182/CesiumForUnrealSamples.log)

Video captures:
Uploading CesiumForUnrealSamples - Unreal Editor 2021-05-02 14-54-52.mp4…

Before:
![Before](https://user-images.githubusercontent.com/20376598/116826728-7819c980-ab63-11eb-939a-2792f4d9831e.PNG)

During:
![During](https://user-images.githubusercontent.com/20376598/116826733-7fd96e00-ab63-11eb-9f5b-c9822f1f427d.PNG)

After:
![After](https://user-images.githubusercontent.com/20376598/116826735-8536b880-ab63-11eb-8b05-97ab541fbc1c.PNG)

After_2:
![After_2](https://user-images.githubusercontent.com/20376598/116826741-8cf65d00-ab63-11eb-863f-783263247483.PNG)

**Comment by baothientran** [comment]
New log with checking for isRenderable() and content:
[CesiumForUnrealSamples.log](https://github.com/CesiumGS/cesium-native/files/6412251/CesiumForUnrealSamples.log)

Video:
https://user-images.githubusercontent.com/20376598/116828249-7d7b1200-ab6b-11eb-91e7-434d943cc445.mp4

Before:
![Before](https://user-images.githubusercontent.com/20376598/116828255-84098980-ab6b-11eb-8e5f-ec140aec2874.PNG)

During:
![During](https://user-images.githubusercontent.com/20376598/116828261-8cfa5b00-ab6b-11eb-8816-3b91ef599cba.PNG)

After:
![After](https://user-images.githubusercontent.com/20376598/116828262-91bf0f00-ab6b-11eb-8553-cf253e5ba56e.PNG)

![After_2](https://user-images.githubusercontent.com/20376598/116828267-95eb2c80-ab6b-11eb-9df5-efd7befb1d07.PNG)

![After_3](https://user-images.githubusercontent.com/20376598/116828272-997eb380-ab6b-11eb-94fe-a4672763bf38.PNG)

**Comment by kring** [comment]
Oh I think I suddenly realized why this happening...

In `ACesium3DTileset::Tick`, we _first_ remove tiles that should no longer be rendered this frame, and _second_ add tiles that should be rendered. That Tick happens in the game thread, of course, but UE has a separate rendering thread. Now as far as I know, there's no "game frame boundary" synchronization involved. Any changes we make in the game thread get pushed out to the rendering thread immediately. The rendering thread only picks up and acts on these changes when it wants to (e.g. at the beginning of the frame), but they're _sent_ immediately. Which means the holes can be caused by a sequence of events like this:

1. In Tick, Cesium decides that some child tiles should be replaced by their parent.
2. The child tiles are removed (`SetVisibility(false)`).
3. At this moment, the rendering thread starts a new frame or whatever such that it picks up the changes so far. The child tiles are removed from rendering.
4. Back in the game thread, the parent tile is added (`SetVisiblity(true)`).
5. It's too late for the parent tile visibility change to be picked up this frame, so there's a hole where it should be.
6. Next frame the parent visibility change is picked up and the hole vanishes.

If this is right, we should see the problem get much worse if we insert a short delay between the code that removes non-longer-visible tiles and the code that adds visible ones. And an easy but not-quite-perfect fix is to flip the order: set new tiles visible before marking old ones non-visible. This may lead to two sets of tiles being rendered in one place for a frame, but that's much better than a hole.

A better fix would require some way to atomically swap the children for the parent. I'm not sure if that's possible in UE.

**Comment by kring** [comment]
The above isn't the full story, because swapping the order doesn't seem to make any difference. Adding a delay makes it worse, but possibly only because it makes the frame rate lower.

**Comment by kring** [comment]
@baothientran is your code that produces the above output available somewhere?

**Comment by baothientran** [comment]
@kring I just pushed it to this branch https://github.com/CesiumGS/cesium-unreal/tree/imagery-bug for cesium unreal. On the cesium-native, there are some helper function to record the prev state and current state as well. It should be in here https://github.com/CesiumGS/cesium-native/tree/tile-log

The main code to print text on the imagery is mostly in this portion of code https://github.com/CesiumGS/cesium-unreal/blob/e77f9a40f7454c00e1b924477fc4a3534a5a1ec7/Source/CesiumRuntime/Private/CesiumGltfComponent.cpp#L279

**Comment by nithinp7** [comment]
@kring @baothientran Thank you both for the extensive debugging around this issue. I'm closing this since the problem seems resolved for now (at least covered up). Pending a future UE fix from Epic, we may roll back the current workaround changes in cesium-unreal.
