### ISSUE TITLE
Evaluate GitHub Action

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cesium-native#204]
Evaluate GitHub Action to see if it can replace our current Travis CI for Linux, MacOS, and Window

**Comment by kring** [comment]
I was reading a bit about GitHub Actions because we're having trouble with Clang on Travis right now. I think moving cesium-native over should be really straightforward, but cesium-unreal will be harder, because:
* GitHub Actions runs Windows and Linux builds on Azure, so we need to take extra steps to avoid spending tons of money copying Unreal Engine down from AWS or GCS on each build. Might just be a matter of making it available on Azure.
* https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners says the runners only have 14 GB of disk space. That won't be enough for Unreal Engine. https://github.community/t/bigger-github-hosted-runners-disk-space/17267/3
