### ISSUE TITLE
Address misc GltfWriter technical debt.

### ISSUE THREAD

**Issue by Samulus** [CesiumGS/cesium-native#213]
https://github.com/CesiumGS/cesium-native/pull/125 was merged before @kring had a chance to point out a few issues.

### Cesium Unreal can't package plugin anymore
```
C:\Users\travis\build\CesiumGS\packages\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumUtility/JsonValue.h(323): error C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```
This step doesn't happen on Travis, and I don't do Unreal builds, so I was unable to catch this before it was merged. This is definitely the most imperative thing that needs to be fixed (compared to all the other issues below).

### Overflow Handling
* The library currently uses `gsl_narrow` to try to detect when large integers are added to the JSON
* Kevin mentioned that values > `2^53` cannot be represented in JavaScript anyway, but https://stackoverflow.com/a/13502497 suggests that they're valid numbers to store in JSON. So if we only care about glTF parsing in web browsers we can gut this complexity and keep everything as doubles. If we want to adhere to the JSON limits and not the JavaScript ones the narrowing can stay.

### Code Generation
* The GltfWriter classes were hand written with the assistance of editor macros to quickly generate each class. This is in contrast to the `CesiumGltfReader` library which uses a collection of JavaScript files to parse gltf schema files to generate C++ code. This was an intentional choice and my previous statements that "it was easier" / "it saved me time" were oversimplifications on my part:
    * The GltfWriter was created as unscoped work during an unrelated sprint, so the goal was to produce something as quickly as possible that would serve as a robust base for extending in `cesium-native`. The existing code generation makes heavy use of ES6 JavaScript templates to dynamically generate code. I thought it was more appropriate to use a template engine like HandlebarJS / Mako / Jinja  to do this. I wanted to refactor the code generation classes by reading dedicated template files and using a proper templating library to inject the necessary changes, but knew there wasn't enough time in the sprint to do this properly so I skipped it. This can be done retroactively, but isn't trivial and needs to be scoped properly.
    
### Misc.

See all the comments here: https://github.com/CesiumGS/cesium-native/pull/125#pullrequestreview-637326983 these are all small issues can be fixed in a single amalgamated PR.

**Comment by kring** [comment]
> Kevin mentioned that values > 2^53 cannot be represented in JavaScript anyway, but https://stackoverflow.com/a/13502497 suggests that they're valid numbers to store in JSON.

Yes, JSON can represent any finite number, even integers greater than 2^64-1 or floating-point numbers with an exponent greater than +/-308.

> So if we only care about glTF parsing in web browsers we can gut this complexity and keep everything as doubles.

Nah that's not quite what I meant. It doesn't have anything to do with web browsers.

Because JavaScript is a major motivator for using JSON (the reason it was created, though it's used much more widely today, of course), and because JavaScript uses double-precision floating point numbers for all of its numbers (even integers), any JSON that uses numbers outside this range is not going to be interoperable with a lot of clients that would potentially want to use it. And therefore such JSON should be avoided. And therefore we're unlikely to see such JSON.

The JSON spec more or less says this near the end of section 6:
https://tools.ietf.org/html/rfc7159#section-6

To try to state it succinctly: JSON with integers greater than 2^53 is not usable with lots of clients, and I don't see any particular reason to go out of our way to make it usable with ours. Just like we don't need to go out of our way to support integers greater than 2^64-1, or floating-point numbers with enormous exponents.

**Comment by kring** [comment]
> I thought it was more appropriate to use a template engine like HandlebarJS / Mako / Jinja to do this.

I'm extremely skeptical this would be an improvement. Mako and Jinja2 are very similar to what we've done, except it's Python instead of JavaScript. I'd argue that developers at Cesium are on average more comfortable with JavaScript than Python, given our history.

We can easily break the templates into separate files without switching languages and template engines. Everything is admittedly a bit mashed together at the moment.

**Comment by Samulus** [comment]
I just realized that the truncation wasn't the only reason I added `std::int64 / std::uint64` widening in JsonValue.h. We were running into a use case exemplified by this test:

```cpp
  SECTION("[0,1,2.5]") {
    CesiumGltf::JsonWriter writer;
    const auto extrasObject =
        Array{std::int64_t(0), std::uint64_t(1), double(2.5)};
    writeJsonValue(extrasObject, writer, false);
    REQUIRE(writer.toStringView() == R"([0,1,2.5])");
  }
```
Instantiating a `JsonValue` with an integer would convert it to a double, and then when you went to serialize it to a string, you would end up with `1.0` instead of `1`. Adding `std::uint64_t` and `std::int64_t` to the `std::varriant` that the `JsonValue` class uses internally fixes this, since you now have a distinctive type. Large integer support was just a bonus. There are still other things that can be done if the added complexity still seems unnecessary:

* The serialization functions can manually check if the value they're serializing is an integer (e.g `if (x == floor(x))`)
* End users will just have to deal with the fact that the library will serialize all their integers to floating point values, semantically `1.0` and `1` are the same thing, and it's safe to cast back in JS / C++ / any language, so this is mostly a style thing anyway

Let me know @kring if you still think the current implementation of `JsonValue` is too complicated and if I should do a follow up PR to do either of the aforementioned alternatives.

**Comment by kring** [comment]
That's interesting @Samulus, I'm a little surprised RapidJSON serializes `double(1.0)` as `1.0` instead of just `1`, given that the latter is shorter and there's no distinction between ints and floats in JSON. By the same token, though, most JSON readers shouldn't make a meaningful distinction between `1` and `1.0`, right?

Anyway, I don't think there's any urgency to making further changes to JsonValue. Let's leave it as-is for now (with separate double/int64/uint64 variants) and see how our opinion evolves as we use it more.

**Comment by kring** [comment]
I wrote some more specific issues and am closing this:
#228 
#229
