### ISSUE TITLE
Review the code for potential thread safety problems

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#215]
<sup>(Note: The actual contents of this issue is written "as if" it referred to a single function of a single class. It does not. There certainly are many places where a review with the appropriate scrutiny would uncover potential race conditions. I'm just using one class and one function as an example here. These "general considerations" will have to be broken down into individual issues that can be addressed via dedicated PRs)</sup>

There have been reports of [occasional crashes](https://github.com/CesiumGS/cesium-unreal/issues/348) in `cesium-unreal`, and the term "occasional" always means that there is some threading issue behind that. (Well, maybe not always. But occasionally...). As an example, some of the traces pointed to [`CreditSystem::createCredit`](https://github.com/CesiumGS/cesium-native/blob/d6587395aa3763799b09d25baa72782b838b9ed5/Cesium3DTiles/src/CreditSystem.cpp#L6). This is currently implemented as

    Credit CreditSystem::createCredit(const std::string& html) {
      // if this credit already exists, return a Credit handle to it
      for (size_t id = 0; id < _credits.size(); ++id) {
        if (_credits[id].html == html) {
          return Credit(id);
        }
      }

      // this is a new credit so add it to _credits
      _credits.push_back({html, -1});

      // return a Credit handle to the newly created entry
      return Credit(_credits.size() - 1);
    }
 
which iterates over a vector and may modify that same vector, so clearly is not thread safe. But looking at possible "call trees" leading to that function, one can see one call to that function in `Tileset.cpp` with:

    this->_externals.pAssetAccessor->requestAsset(this->_asyncSystem, ionUrl)
      .thenInMainThread([this](std::shared_ptr<IAssetRequest>&& pRequest) {
        this->_handleAssetResponse(std::move(pRequest));
      })

via

    void Tileset::_handleAssetResponse(std::shared_ptr<IAssetRequest>&& pRequest) {
        ...
          this->_tilesetCredits.push_back(
              this->_externals.pCreditSystem->createCredit(
              html->value.GetString()));

and one call from `BingMapsRasterOverlay.cpp` with

    Future<std::unique_ptr<RasterOverlayTileProvider>>
    BingMapsRasterOverlay::createTileProvider( 
      ...
      ) {
      ...
      return pAssetAccessor->requestAsset(asyncSystem, metadataUrl)
          .thenInWorkerThread(
          [ ... ](std::shared_ptr<IAssetRequest> pRequest)
              -> std::unique_ptr<RasterOverlayTileProvider> {
            ...
              credits.push_back(
                  {pCreditSystem->createCredit(
                   creditString->value.GetString()),
                   coverageAreas});

and from a *very* quick glance, this looks like the function is once called via `thenInMainThread` and once via `thenInWorkerThread`. 

This *specific* issue can probably be solved easily: Wrapping the work of `createCredit` into some mutex, and explicitly adding a `/** This function can be called from any thread */` hint in the docs. 

But more generally, we should allocate some time for examining the functions that may be called from multiple threads, review their actual call sites, and maybe try to more diligently add prominent comments like `/* May only be called from thread X*/` or `/* May be called from any thread */`.

**Comment by kring** [comment]
Good analysis Marco, that definitely looks like a true race condition to me. And auditing for other similar cases is definitely worthwhile.

**Comment by javagl** [comment]
One could argue that *this particular case* is unlikely to be the reason for the crashes in the linked issue (I think there was no BingMaps involved). But this was only an example to show that there definitely *are* cases where such functions are called from multiple threads. Looking at the call sites and "going up" the call tree, until the calling thread is known, may bring some insights. 

More specifically: I assume that the credit system *should* be thread safe (with some mutex here and there). In other cases, the issue might be causes by some resource (that is *not* supposed to be thread safe) being used by "the wrong" thread *accidentally*.

**Comment by kring** [comment]
> I assume that the credit system should be thread safe

Yep, similar to the other interfaces like `IAssetAccessor`. I think it will be ok performance-wise to just put all of `createCredit` in a mutex, though it's definitely possible (but not easy) to do less locking if it ever becomes a hotspot.

It probably doesn't affect the solution at all, but just for background and context... the `createCredit` call in `_handleAssetResponse` probably can't race with any of the others, because it will complete before any other tiles are downloaded and therefore before any other credits are created. But multiple raster overlay tiles can and will be loaded simultaneously, so the createCredit in `BingMapsRasterOverlay::createTileProvider` will race with itself and with other similar work happening in a worker thread.

**Comment by kring** [comment]
The specific case mentioned in this issue was fixed in #232, and our threading policy (no instances can be shared between threads unless the type's documentation explicitly says otherwise + don't pass non-thread-safe objects to work threads at all) is doing a decent job of avoid race conditions. We need to be constantly vigilante of course, but I don't think there's any particular action for this issue, so I'm closing it.
