### ISSUE TITLE
CesiumGltf::Model::merge does not combine extras

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-native#289]
Gltfs can be combined with the `CesiumGltf::Model::merge(...)` function. We currently use this merge function to combine all the inner tiles of a composite tile into a single gltf. It looks like the merging does not combine the extras however, it just keeps the extras from the first inner tile. This so far has not become a problem since the only usage of extras in cmpt tiles has been RTC_CENTER, which (I think) is always the same between inner tiles.

I was planning on fixing it, but just wanted to check if this was intended first. 
cc: @baothientran

**Comment by baothientran** [comment]
ah I maybe wrong but the merge function probably doesn't work correctly with extensions either. For example, it tries to combine buffers all together into a single array, and update buffer indices accordingly. But it doesn't do that for extension. For example, when we try to merge a normal gltf with another gltf with draco extension, the index of buffer view in the draco extension is not updated after the merge https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md. It's similar for EXT_feature_metadata extension.

@kring Maybe it's simpler to have a vector of gltf per tile instead of a single gltf?

**Comment by baothientran** [comment]
wait never mind, I see it does for draco extension,bBut not for `EXT_feature_metadata` which also needs to be updated

**Comment by kring** [comment]
It's intentional. At least, it's documented that extras are not copied. We could do something simple, like dump all the sub-model extras into a list on the `extras.submodels` property or somesuch, but that might be worse than the current scenario because not even the first model's extras will be "in the right place" anymore.

We could also do a deep merge of the extras from each sub-model: the new extras is the union of all submodel extras properties, and when multiple models have a given property, we... do something. Put all the values in an array? Last one wins? Make it an option? But all of these possibilities could fail quite badly if the extras ever refer to other glTF objects (e.g. an accessor), because we have no reliable way to update indices.

So in the absence of a clear use-case for combining extras, it seemed prudent to just use the extras from the first model because it's easy and reliable (won't break object references).

**Comment by kring** [comment]
> Maybe it's simpler to have a vector of gltf per tile instead of a single gltf?

Simpler for cesium-native, sure. But it pushes the burden onto every client instead. I don't think we should go that way.

Also FWIW the "bug" label is inaccurate since the behavior is intentional and clearly documented.

**Comment by baothientran** [comment]
whoops sorry I didn't notice the comment on the method

**Comment by nithinp7** [comment]
Copied from slack: 
It appears that composite tiles may have inner tiles with different RTC_CENTER values, some inner tiles may not have them at all. Currently RTC_CENTER is passed on through the extras. The issue is that composite tile's inner gltfs are merged into a single gltf, and there's not a generalized way to merge extras (and so RTC_CENTER ends up just arbitrarily picking the RTC_CENTER from the first inner tile). Would it be reasonable to remove RTC_CENTER from the unreal-native interface altogether, and instead factor in the RTC_CENTER value into the top level node transforms on the native side?

**Comment by baothientran** [comment]
@nithinp7 do you mean something like this?
```
                                  merged-root-node (identity matrix)
1st gltf root (RTC transform)                             2nd gltf root (RTC transform) 
```

I think it should be reasonable if it works (which I think it is) and we don't have to worry about extra

**Comment by nithinp7** [comment]
@baothientran Yup exactly! It's probably still an open decision whether we should do this in the merge function or in the content loaders. For instance if we were to do it in each content loader, i.e. receive RTC_CENTER and update all top level nodes, we could remove the need for RTC_CENTER in the extras completely, even for non-composite tiles.

**Comment by baothientran** [comment]
I prefer it to be in the content loader, so you can get the above node for free when using merge function. Also unreal side won't have to deal with extra

**Comment by kring** [comment]
Closing this because I don't think there's any action here that isn't captured elsewhere.
