### ISSUE TITLE
Access Violation In copyDecodedAttribute function

### ISSUE THREAD

**Issue by lyhkop** [CesiumGS/cesium-native#400]
in this code:
`
const auto doCopy = [pMesh, pAttribute, numberOfComponents](auto pOut) {
    for (draco::PointIndex i(0); i < pMesh->num_points(); ++i) {
      const draco::AttributeValueIndex valueIndex = pAttribute->mapped_index(i);
      pAttribute->ConvertValue(valueIndex, numberOfComponents, pOut);
      pOut += pAttribute->num_components();
    }
};
`
pMesh->num_points() maybe greater than pOut size which reference buffer.cesium.data，that will causes 'memory access violation

'

**Comment by kring** [comment]
Yes I think you're right @lyhkop. Here's the specific code:
https://github.com/CesiumGS/cesium-native/blob/e8cac1748afb0495dd127712774f1444483f4fef/CesiumGltfReader/src/decodeDraco.cpp#L234

A simple solution is to change:

```
for (draco::PointIndex i(0); i < pMesh->num_points(); ++i) {
```

To:

```
for (int64_t i = 0; i < pAccessor->count; ++i) {
```

Because pAccessor->count is guaranteed to be `<= num_points()` by a check earlier in the code.
