### ISSUE TITLE
Support EXT_mesh_features

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-native#407]
@kring I haven't fully dived into the spec differences between this and EXT_feature_metadata yet, but just to take inventory of the things that need to be done:
* Add the EXT_mesh_features extension
* Refactor upgradeBatchTableToFeatureMetadata so that it actually upgrades to mesh_features instead.
* On the Unreal side, refactor FCesiumMetadataPrimitive (maybe just the constructor?) Will the in-memory representation of primitive metadata be the same, do the actual structures and metadata access api need any change? 
* Add FCesiumMetadataTexture (or some such name) and an api to access this on the cpu.
* Styling? Is this just for metadata textures or for per-vertex metadata as well? 
  * For metadata textures: can we send the texture itself straight to Unreal with a NEAREST filter, then in the fragment shader sample the feature id for that texel, and then do a color lookup in the fragment shader based on the id? Can the fragment shader part be deferred to the user, who presumably knows more about the tileset and the desired id-based coloring?
  * For per-vertex metadata styling, we'll need to hack a way to send feature ids as vertex data, probably sneak it through as a UV coordinate.

Does this list sound about right? Are there any huge pieces I'm missing?

**Comment by kring** [comment]
> Add the EXT_mesh_features extension

👍 

> Refactor upgradeBatchTableToFeatureMetadata so that it actually upgrades to mesh_features instead.

👍 

> On the Unreal side, refactor FCesiumMetadataPrimitive (maybe just the constructor?) Will the in-memory representation of primitive metadata be the same, do the actual structures and metadata access api need any change?

I'm not too familiar with what's _different_ between the two specs. If the changes suggest API changes - e.g. new names, new concepts, etc -  we should go ahead and evolve the API to match the spec. But no changes needed otherwise.

> Add FCesiumMetadataTexture (or some such name) and an api to access this on the cpu.

👍 

> Styling?

Let's treat this as a separate issue, as it could easily be 10x the work of everything else here put together. :)

> For per-vertex metadata styling, we'll need to hack a way to send feature ids as vertex data, probably sneak it through as a UV coordinate.

Static meshes have a "vertex color" that I believe is commonly used for this purpose. We're already using it for... actual vertex coloring though. So we'll have to figure out something there. Maybe even move to a custom static mesh class if necessary.

**Comment by ptrgags** [comment]
@nithinp7 just to make sure you're aware, the `EXT_mesh_features` spec has a [changelog](https://github.com/CesiumGS/glTF/blob/proposal-EXT_mesh_features/extensions/2.0/Vendor/EXT_mesh_features/README.md#revision-history) at the bottom
