### ISSUE TITLE
Replace a lib file built from cesium native, open editor, editor crash.

### ISSUE THREAD

**Issue by lidongzhuo** [CesiumGS/cesium-native#513]
I successfully compiled cesium native. I replace a library file of original CesiumForUnreal plugin which is referenced by the project of CesiumForUnrealSamples. The project an be built successfully. When I open the project, the UE editor crash.
I also did this test: 1.replace lib file. 2.compile CesiumForUnreal plugin using command line. 3.replace whole CesiumForUnreal plugin. But the editor would still crash when I open the project.
Is there something wrong with my way of lib replacement? Or do we have instructions for use of cesium native after compile?

**Comment by kring** [comment]
cesium-native needs to be compiled with particular options in order to work with Cesium for Unreal. Follow the procedure in the Developer Setup Guide:
https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup.md

Most importantly, you need to invoke cmake from cesium-unreal `extern` directory, not from the cesium-native root.

I'm going to close this, but if you have further questions please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by lidongzhuo** [comment]
I understood. Thank you very much.
