### ISSUE TITLE
Find best method for organizing developer documentation

### ISSUE THREAD

**Issue by HolenWu** [CesiumGS/cesium-native#619]
Hi, may I ask why I can't find a developer manual about Cesium Native? It's hard to fully understand it only from the source code.

**Comment by timoore** [comment]
The individual classes in cesium-native are reasonably well documented. I studied [cesium-unreal](https://github.com/CesiumGS/cesium-unreal) hard in order to write [vsgCs](https://github.com/timoore/vsgCs).

**Comment by DengSenHandsome** [comment]
@kring

**Comment by j9liu** [comment]
Since we have #832 to actually _publish_ our Doxygen-generated documentation, I'd like to repurpose this issue for the actual organization.

Our Doxygen docs will be on the website regardless, but it will take more resources to actually help users understand what's going on. For instance, see #982 , #981 , #980.

We should figure out the best place for these resources to live. Should we our resources:

- Be markdown files stored in the cesium-native repo?
- Live on the website somewhere?
- Both?

It could even be worth taking advantage of our learning platform at https://cesium.com/learn/ to create an entirely separate category for Cesium Native. The "tutorials" could walk through how a simple integration with Cesium Native could look like, and host other written documentation for concepts that users would need to know.

**Comment by kring** [comment]
I'd like to advocate for keeping the cesium-native docs in markdown and in the same repo as the code. Because:
1. cesium-native is inherently a developer product. The polish of the web site isn't as essential.
2. Managing content in the web site CMS adds a ton of friction for us.
3. Keeping docs in the repo makes versioning basically free. On the web site, it's a nightmare.

**Comment by j9liu** [comment]
Closing this issue. We have decided to keep put these docs in doxygen, and these docs will be published every release to https://cesium.com/learn/cesium-native/ref-doc/.
