### ISSUE TITLE
Http requests fail with error 401 when using CachingAssetAccessor

### ISSUE THREAD

**Issue by TheMostDiligent** [CesiumGS/cesium-native#684]
Apparently this happens because the request containing the access token (e.g. `https://api.cesium.com/v1/assets/2/endpoint?access_token=<TOKEN>`) is cached and is never issued. After that any HTTP request fails with error code 401 (Unauthorized) and the following message body:

```
{"code":"InvalidCredentials","message":"Invalid access token"}
```

**Comment by kring** [comment]
Can you tell us how to reproduce this? I wouldn't expect this to be a problem because: 1) the `assets/#/endpoint` service should have cache headers indicating it should not be cached, and the CacheAssetAccessor should honor that, and 2) an expired token should trigger a refresh of the token (it may log the 401 errors, but it should continue working after the token is successfully refreshed).

**Comment by TheMostDiligent** [comment]
> the assets/#/endpoint service should have cache headers indicating it should not be cached, and the CacheAssetAccessor should honor that

Thank you for the hint - there was an issue on our side where we did not pass the server headers to cesium-native, so that it cached everything. After we fixed this, everything seems to be working fine.
