### ISSUE TITLE
Dynamic TilesetContentLoader

### ISSUE THREAD

**Issue by carlopiersanti** [CesiumGS/cesium-native#695]
Hello,

For a specific development I need to implement a subclass of TilesetContentLoader

It will be a octree whose LoadTileContent and CreateTileChildren methods are dynamic i.e. the structure and the contents of the tree will evolve during time occording to external factors. These evolutions will be very frequent so I can't just recreate a tileset every time.

My question is : Do I need to do something specific to make Tileset::updateView work or will it work out of the box ?

I see in the method Tileset::_unloadCachedTiles these methods calls

this->_pTilesetContentManager->unloadTileContent(*pTile);
this->_loadedTiles.remove(*pTile);

Do I need to implement a similar mechanism to remove the updated tiles ?

Thanks and regards

**Comment by kring** [comment]
It's likely to be quite challenging. The first problem you'll face is that modifying the `_children` vector on `Tile` will invalidate pointers to the tiles it contains. So parent pointers, for instance, will be invalidated. There are other cases, too, where pointers to Tiles are held by asynchronous processes on the assumption that they will continue to be valid.

I can think of two ways to fix this:
1. Change `_children` to `std::vector<std::unique_ptr<Tile>>` instead of just `std::vector<Tile>`. This will require a lot more heap allocations for tiles (which is why we didn't do it in the first place), but it will avoid the problem of modifications to the vector invalidating Tile pointers.
2. Pre-allocated the maximum number of Tile instances you'll need, and have some way to mark them "unused". This will use more memory, of course.

There are likely to be other challenges as well, that's just the first big one that comes to mind. If you're only ever modifying Tile content, rather than modifying the actual structure of the Tile tree, things will be easier. Not easy, but easier.
