### ISSUE TITLE
Expose 3D Tiles feature attributes

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#71]
Because tiles are "sent" to the renderer as glTFs, we should consider encoding feature attributes the way they [are / will be] encoded in 3D Tiles Next.

**Comment by kring** [comment]
3D Tiles Next will use the the [EXT_feature_metadata](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_feature_metadata) extension embedded in the tile glTF to encode feature metadata. So we'd like to use this extension to communicate feature data coming from cesium-native as well. That means converting b3dm batch tables to `EXT_feature_metadata` on load. There are some challenges to that:

* `EXT_feature_metadata` only supports binary properties, not JSON ones. So batch table JSON properties need to be converted to binary.
* `EXT_feature_metadata` requires that a given property have the same _type_ across all features. The b3dm batch table is more flexible when encoded in JSON. So we'll have to convert all values to a common representation when converting the batch table. i.e. convert mixed-type properties to strings.
* `EXT_feature_metadata` does not allow a property to have a "null" value for a particular property. So here, too, we'll need to convert nulls to zero-length strings.
* `EXT_feature_metadata` does not support anything like the `3DTILES_batch_table_hierarchy` extension. So the hierarchy will need to be flattened into parallel arrays. This will likely introduce nulls, which will in turn require types to be widened to strings.

As `EXT_feature_metadata` evolves, or as further extensions with more capability are added, we can revisit these concessions. But this will likely be "good enough" for most tilesets.

**Comment by kring** [comment]
This code from CesiumJS may be useful: https://github.com/CesiumGS/cesium/blob/master/Source/Scene/parseBatchTable.js

**Comment by baothientran** [comment]
Current progress from @kring:
https://github.com/CesiumGS/cesium-unreal-samples/tree/picking
https://github.com/CesiumGS/cesium-unreal/tree/picking
https://github.com/CesiumGS/cesium-native/tree/feature-metadata-extension

On the native side, the TODOs are:
- [ ] Add support for binary b3dm batch tables
- [ ] Add support for string and array metadata
- [ ] Add support for the 3D Tiles batch table hierarchy extension

On the unreal side, TODOs are:
- [ ] upport all the metadata types (currently only int8 and float64 are supported)
- [ ] Handle float64 properly; slightly tricky cause glTF doesn't have float64 accessors.
- [ ] Figure out how we can package the actual picking functionality into something more useful for our users. Currently it's a dodgy part of the level blueprint in cesium-unreal-samples.

**Comment by baothientran** [comment]
@kring the common API to access both b3dm and EXT_feature_metadata is in the https://github.com/CesiumGS/cesium-native/tree/feature-metadata-api branch. This is a high level API to access both batch table and gltf EXT_feature_metadata without the need to transcoding from one format to the other. 

The high level design is that we have an abstract `Metadata` class and 5 `PropertyView` classes. The Metadata is mostly just a simple map from a property name to a `PropertyView` object. For `PropertyView` class, we have PrimitivePropertyView to represent scalar, `StringPropertyView` to represent string, "ArrayPropertyView" to represent array (this should work for fixed and dynamic array), `JsonPropertyView` to represent json, and `StructPropertyView` for struct. Those PropertyView classes represents the whole collection of instances similar to how batch table work. For example, in the batch table, if ID is a collection of Unsigned Int of instances, then we have a PrimitivePropertyView to represent the array of Unsigned Int similar to that.

So to bridge the difference between batch table and EXT_feature_metadata, we would need to implement those 5 properties for each format, and then on Unreal side, it will only deal with those high level API rather than using the batch table directly. Similar for EXT_feature_metadata. To transcoding from one to the other, one can create Transcoder class and only deal with those high level API rather than the format itself. Please let me know if we should go ahead with it

**Comment by baothientran** [comment]
@kring I forget to mention, the whole code mostly in CesiumMetadata directory

**Comment by kring** [comment]
Thanks @baothientran. I took a look at the `feature-metadata-api` branch, and I guess the main thing I'm unclear on is how this will connect with what we already have. Will there be a new extension to hold a `Metadata` instance? An additional `Metadata` property on `TileContentLoadResult`?

The problem is, I don't really like either of those options.

It seems like a bad idea to have cesium-native specific glTF extensions. Especially when we already have a new extension for metadata that we're in the process of defining, `EXT_feature_metadata`. It doesn't capture everything in the b3dm batch table with perfect fidelity, of course. If that matters, we should fix the `EXT_feature_metadata` extension. If it doesn't matter (because we don't think anyone is using the missing features for anything important, or there are acceptable alternative ways to do it), then that should be good enough for cesium-native too.

On the other hand, if we put a Metadata instance in `TileContentLoadResult`, we're moving away from the ideal scenario where glTF (a well-designed and extensible standard!) is the native language of cesium-native and used to communicate everything about a model/tile to any rendering engines or other applications that use it.

So I think I would still rather see batch table transformed into EXT_feature_metadata. We should provide helpers, along the lines of AccessorView and AccessorWriter to make it easier to read and write feature data stored as EXT_feature_metadata. Ideally, we'd be able to use AccessorView and AccessorWriter directly. The writer would be used by Batched3DModelContent to do the conversion. I think that's putting our engineering effort where it belongs - our new EXT_feature_metadata extension - rather than in creating abstractions over legacy stuff like the b3dm batch table.

**Comment by baothientran** [comment]
gsl::span is so painfully close to be an ideal interface for an array property type. What it can't represent is the array of string or maybe array of bool (I haven't tested it yet but my gut say it can't because boolean is bit pack together similar `std::bitset`). For array of string, it typically uses one buffer to store value and two offset buffers to represent array length and string length (https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/specification/Metadata/1.0.0#arrays-1). Unfortunately gsl::span doesn't have the concept of offset, so it's not possible without additional allocation. The only solution is to create a custom array view and specialize it for those cases, e.g `ArrayView<std::string_view> or ArrayView<bool>`

**Comment by baothientran** [comment]
The implementation for the property view is in this link https://github.com/CesiumGS/cesium-native/blob/feature-metadata-extension/CesiumGltf/include/CesiumGltf/PropertyAccessorView.h

**Comment by kring** [comment]
@baothientran your second design definitely looks better to me. You can also provide a method to create a PropertyAccessorView and dispatch it to statically-typed callback, rather than requiring the user to manually switch on the type. Take a look at `createAccessorView` in `AccessorView.h`. So using it would look something like this:

```cpp
struct PropertyVisitor {
  void operator()(const PropertyAccessorView<int32_t>& view) {
   for (size_t instanceIdx = 0; instanceIdx < view.size(); ++instanceIdx) {
        int32_t value = view[instanceIdx];
   }
  }

  void operator()(const PropertyAccessorView<std::string_view>& view) {
    // ...
  }
  
  template <typename T>
  void operator()(const PropertyAccessorView<T>& view) {
    // catch all for other types of properties
  }
};

ModelEXT_feature_metadata& metadata = ...;

// We can add properties directly to ModelEXT_feature_metadata by using
// the `toBeInherited` property in glTF.json, so maybe we don't need a separate
// MetadataView class at all?
metadata.createView("Height", PropertyVisitor{});
```

**Comment by baothientran** [comment]
while I implement blueprint library for metadata, I just realize it doesn't support `uint64` and `double`. I'm not sure what to do with those cases

**Comment by lilleyse** [comment]
CesiumJS has the same dilemma for GPU styling and may require lossy fallbacks/warnings https://github.com/CesiumGS/cesium/issues/9572

**Comment by baothientran** [comment]
ah I see it converts uint64 to float instead of int64. Good point! I guess we can live with the lossy keyword for blueprint for now

**Comment by baothientran** [comment]
@kring This is probably a minor problem, but I think it's better to discuss here. Currently, to access metadata, we have `*View` classes to inspect the data. On the Unreal side, I currently wrap those classes in the USTRUCT to be used with the blueprint. However, one problem is that because those classes don't own the metadata storage (e.g gltf buffer), it requires Gltf Model to be around until the tile is evicted from the cache. So it is probably a little wasteful since we can remove the mesh data right away once we are done creating unreal resources. In the case that we need to remove gltf model to free more memory, the metadata need to copy  and own the metadata buffers. So between the two options a) keeping the gltf model around and use the view classes and b) has the metadata owns the its buffers, what's your opinion on them? Or maybe a compromise in the future is that we can have both just like we have `std::string` and `std::string_view`

**Comment by kring** [comment]
@baothientran we currently don't unload the glTF data even once we've created the Unreal resources, right? Doing so might be a useful optimization, but it definitely raises some problems, so we'd have to approach it cautiously. Unless I've missed something, I don't think we need to worry about it currently. Our solution to that might be impacted by how we make feature metadata available to Materials as well.

**Comment by baothientran** [comment]
nope we still keep the gltf currently. The above problem is just a small assumption, but it doesn't affect much with the current implementation of metadata on unreal side
