### ISSUE TITLE
After loading meshopt compressed model, it can't be exported as uncompressed glb, and can't be restored to normal glb model.

### ISSUE THREAD

**Issue by xinghaoyujianni** [CesiumGS/cesium-native#769]

**Comment by xinghaoyujianni** [comment]
[meshopt_compress.zip](https://github.com/CesiumGS/cesium-native/files/13448407/meshopt_compress.zip)
The zip is the compressed model, he can be loaded properly by http://gltf.bimant.com/

**Comment by kring** [comment]
As always when writing a bug report (for any product, not just cesium-native), you need to provide:
1. What exactly have you done?
2. What happens when you've done this?
3. What did you expect to happen instead?

We can't understand what is wrong - nevermind fix it - from the information you've provided so far.

**Comment by wallabyway** [comment]
gltf-transform can restore this to an uncompressed glTF file.

https://gltf-transform.dev

have you tried that ?
