### ISSUE TITLE
Cannot git cesium native using instructions on webpage 

### ISSUE THREAD

**Issue by bclay1297** [CesiumGS/cesium-native#947]
I tried git clone git@github.com:CesiumGS/cesium-native.git --recurse-submodules in a command windows
and I get the following error message 
Cloning into 'cesium-native'...
The authenticity of host 'github.com (140.82.112.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

If I download the zip file from git and try to CMake it fills my C drive then then aborts

Bruce

**Comment by kring** [comment]
@bclay1297 have you configured your git client for ssh access to github?
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh

If you have trouble getting SSH to work, you could always try cloning over https instead:

```
git clone --recurse-submodules https://github.com/CesiumGS/cesium-native.git
```

I'm closing this because it's either a problem with your configuration or a connectivity problem with GitHub, and in either case not something that we can fix.
