### ISSUE TITLE
Handling of duplicate resources

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#96]
There might already be decision on how this should be handled - maybe only implicitly, or maybe by ~"doing it the same way as CesiumJS" - but: What is the intended strategy for handling duplicate resources? 

When there is a Tileset that refers to the same `"content.uri" = "http://example.com/content.b3dm"`, multiple times, then the requests are going out repeatedly, the responses are handled repeatedly, and all the resource handling functions (`prepareInMainThread`, `free` etc) are called repeatedly, The performance implications of this may obviously overshadow *any* other optimization.  

There are, *very* roughly speaking, different levels on which this could be addressed:

- It could all be left to some omniscent caching infrastructure. (Handwavingly: ~"What the browser does", or "On the networking level", "With some local proxy"). This would still mean that cesium-native has to do the same work again and again.
- The request could be sent out only **once**. This would mean that there is some sort of `set<string> urlsForWhichRequestsAreInFlight` somewhere. This might require some thought to find a sensible structure. (The fact that there might be multiple, distinct URLs that point to the same resource should not be sooo important. But the URLs [sh/c]ould be *normalized* at least, so that `/foo/.../bar.b3dm` and `/bar.b3dm` are considered to be equal). 
- The response could be processed only once (essentially meaning that the *request* will be sent out multiple times, but the *response* is stored in some sort of lookup - there may be things to consider that I don't have on the radar in all detail, like server-side caching or resources that might change over time...).

**Comment by kring** [comment]
I think a large part of this has been addressed by the SQLite-based disk cache in `CachingAssetAccessor`. That will avoid duplicate requests, but will still parse the response multiple times (as well as create duplicate textures, etc). I am going to close this, though, because it's not actionable in its current form, and if and when we find a tileset that would benefit from caching of parsed responses, I don't foresee any problems implementing it in cesium-native without a breaking change.
