### ISSUE TITLE
Fix Documentation CI task

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-native#983]
Currently the Documentation CI task takes a while because it builds all the vcpkg dependencies unnecessarily. Fixing this will make the steps below faster.

**Comment by j9liu** [comment]
Forgot to include: we should also review Doxygen log and fix problems it reports.

Additionally, we should change CI Documentation task to fail on Doxygen errors so that we avoid them going forward.

**Comment by kring** [comment]
I wanted to mention a cool feature while I'm thinking about it, because I almost forgot about it myself. We have the ability to pull examples from tests and include them in the generated docs. Which is pretty nice because it allows us to make sure the examples compile and even function correctly. See the docs for the `Plane` constructors for an example:
https://cesium.com/learn/cesium-native/ref-doc/classCesiumGeometry_1_1Plane.html#a80cb61ea891fe39d6468eca8dbb67291

**Comment by azrogers** [comment]
Split off fixing issues in the Doxygen log into issue #1010 to better keep track.

**Comment by kring** [comment]
Fixed in #1011.
